version: '3'

networks:
  default:
    external:
      name: my_net

services:
# https://github.com/alexanderschnitzler/docker-mysqldump
  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    container_name: 360daycare-web
    image: 360daycare
    working_dir: /website
    volumes:
      - ./:/website
    depends_on:
      - 360daycareredis
    networks:
      - my_net
  #Nginx Service
  360daycarenginx:
    image: nginx:alpine
    container_name: 360daycare-nginx
    restart: always
    ports:
       - "8282:80"
    volumes:
      - ./:/website
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    networks:
      - my_net
#   #MySQL Service
#   360daycaredb:
#     image: mariadb:latest
#     restart: always
#     container_name: 360daycare-db
#     environment:
#        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#       #  - MYSQL_ALLOW_EMPTY_PASSWORD=1
#        - MYSQL_DATABASE=${DB_DATABASE}
#        - MYSQL_USER=${DB_USERNAME}
#        - MYSQL_PASSWORD=${DB_PASSWORD}
#     ports:
#       - "33091:3306"
#     volumes:
#       - mariadb_web_data:/var/lib/mysql/
# #    networks:
# #      - app-network
  360daycareredis:
    image: redis:alpine
    restart: always
    container_name: 360daycare-redis
    ports:
    - 6383:6379
##Docker Networks
networks:
  my_net:
    external:
      name: my_net
#Volumes
# volumes:
#   mariadb_web_data:
#     driver: local

